"""Operator-edited CONFIG BLOCK (v4.4 'edit these freely' ethos). SPEC §10.

Runtime truth for ordermin/costmin/lot_decimals is the `pairs` table, refreshed
from AssetPairs at startup + daily. The numbers below are SEED/FALLBACK only —
never trusted as truth (SPEC §7 F8, Appendix C).
"""
import os
import logging

_log = logging.getLogger(__name__)

# Paths (single 916G root disk; project island under home). RULINGS env ruling.
_PKG_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(_PKG_DIR)
DB_PATH = os.path.join(PROJECT_ROOT, "deepfield.db")
LOG_DIR = os.path.join(PROJECT_ROOT, "logs")

# Backfill/live intervals (minutes). SPEC §6.
# INTERVALS is what we INGEST, store, backfill and gap-heal — the operator's
# "broaden our horizons" (2026-07-19). SIGNAL_INTERVALS is what drives scoring and
# the ORDER PATH, and the two are deliberately not the same list.
#
# Why they must stay split: ingest.handle_candle_closed edge-gates on the close
# INSTANT per symbol (close_at > _last_fired[symbol]), not per interval, because
# daily and weekly close at the same instant every Thu and that collapsed a real
# double-order. Feeding fast intervals into that same gate would (a) re-fire the
# confirmed-BUY path on EVERY 15m close — 96 order attempts/day/symbol instead of
# ~2 — and worse (b) the boot seed takes max(close_instant) across the list, so a
# 15m bar closing minutes ago would seed _last_fired PAST the daily close instant
# and silently suppress daily entries after every restart. The strategy is a
# weekly/daily cycle thesis (6 of 7 signals are weekly); fast bars are data to
# look at, not a trigger to trade on.
#
# Kraken's OHLC enum is 1/5/15/30/60/240/1440/10080/21600 — there is NO monthly
# candle (21600 is 15 days), which is why monthly is DERIVED in engine
# .monthly_closes() by sampling every 4th weekly close for the regime M-RSI.
# Depth is capped at 720 rows per fetch regardless of `since`, so history per
# interval is bounded: 15m ~7.5d, 1h ~30d, 1d ~2y, 1w ~13.8y. Fast intervals
# accumulate forward from switch-on; they cannot be backfilled deeper.
INTERVALS = (15, 60, 1440, 10080)
SIGNAL_INTERVALS = (1440, 10080)

# v1 asset code -> v2 symbol normalization (the rename traps). SPEC §6.
NORMALIZE = {"XBT": "BTC", "XDG": "DOGE"}

# --- Pairs (Appendix C) — regenerated by scripts/gen_roster.py from a live
# AssetPairs snapshot (operator dispatch 2026-07-19: full margin universe). ---
# ws_symbol is derived from wsname via NORMALIZE at runtime; precomputed here.
PAIRS = [
    # rest, wsname, ws, display, ordermin, costmin — full margin universe
    # (operator dispatch 2026-07-19: EVERY online USD margin pair, no filter).
    # ordermin/costmin are SEED/FALLBACK only — the pairs table refreshes from
    # AssetPairs at startup + daily. Incumbent 21 first, then by max-lev desc.
    {"rest": "XXBTZUSD",    "wsname": "XBT/USD",      "ws": "BTC/USD",      "display": "BTC",      "ordermin": 5e-05,    "costmin": 0.5},
    {"rest": "XETHZUSD",    "wsname": "ETH/USD",      "ws": "ETH/USD",      "display": "ETH",      "ordermin": 0.001,    "costmin": 0.5},
    {"rest": "XXRPZUSD",    "wsname": "XRP/USD",      "ws": "XRP/USD",      "display": "XRP",      "ordermin": 1.65,     "costmin": 0.5},
    {"rest": "SOLUSD",      "wsname": "SOL/USD",      "ws": "SOL/USD",      "display": "SOL",      "ordermin": 0.06,     "costmin": 0.5},
    {"rest": "SUIUSD",      "wsname": "SUI/USD",      "ws": "SUI/USD",      "display": "SUI",      "ordermin": 5,        "costmin": 0.5},
    {"rest": "XDGUSD",      "wsname": "XDG/USD",      "ws": "DOGE/USD",     "display": "DOGE",     "ordermin": 50,       "costmin": 0.5},
    {"rest": "XLTCZUSD",    "wsname": "LTC/USD",      "ws": "LTC/USD",      "display": "LTC",      "ordermin": 0.1,      "costmin": 0.5},
    {"rest": "LINKUSD",     "wsname": "LINK/USD",     "ws": "LINK/USD",     "display": "LINK",     "ordermin": 0.55,     "costmin": 0.5},
    {"rest": "ADAUSD",      "wsname": "ADA/USD",      "ws": "ADA/USD",      "display": "ADA",      "ordermin": 20,       "costmin": 0.5},
    {"rest": "AVAXUSD",     "wsname": "AVAX/USD",     "ws": "AVAX/USD",     "display": "AVAX",     "ordermin": 0.5,      "costmin": 0.5},
    {"rest": "AAVEUSD",     "wsname": "AAVE/USD",     "ws": "AAVE/USD",     "display": "AAVE",     "ordermin": 0.05,     "costmin": 0.5},
    {"rest": "UNIUSD",      "wsname": "UNI/USD",      "ws": "UNI/USD",      "display": "UNI",      "ordermin": 1.5,      "costmin": 0.5},
    {"rest": "DOTUSD",      "wsname": "DOT/USD",      "ws": "DOT/USD",      "display": "DOT",      "ordermin": 3.9,      "costmin": 0.5},
    {"rest": "BCHUSD",      "wsname": "BCH/USD",      "ws": "BCH/USD",      "display": "BCH",      "ordermin": 0.01,     "costmin": 0.5},
    {"rest": "ALGOUSD",     "wsname": "ALGO/USD",     "ws": "ALGO/USD",     "display": "ALGO",     "ordermin": 41,       "costmin": 0.5},
    {"rest": "CRVUSD",      "wsname": "CRV/USD",      "ws": "CRV/USD",      "display": "CRV",      "ordermin": 20,       "costmin": 0.5},
    {"rest": "HBARUSD",     "wsname": "HBAR/USD",     "ws": "HBAR/USD",     "display": "HBAR",     "ordermin": 55,       "costmin": 0.5},
    {"rest": "PEPEUSD",     "wsname": "PEPE/USD",     "ws": "PEPE/USD",     "display": "PEPE",     "ordermin": 1500000,  "costmin": 0.5},
    {"rest": "SHIBUSD",     "wsname": "SHIB/USD",     "ws": "SHIB/USD",     "display": "SHIB",     "ordermin": 770000,   "costmin": 0.5},
    {"rest": "TRXUSD",      "wsname": "TRX/USD",      "ws": "TRX/USD",      "display": "TRX",      "ordermin": 16,       "costmin": 0.5},
    {"rest": "XZECZUSD",    "wsname": "ZEC/USD",      "ws": "ZEC/USD",      "display": "ZEC",      "ordermin": 0.01,     "costmin": 0.5},
    {"rest": "USDCUSD",     "wsname": "USDC/USD",     "ws": "USDC/USD",     "display": "USDC",     "ordermin": 5,        "costmin": 0.5},
    {"rest": "HYPEUSD",     "wsname": "HYPE/USD",     "ws": "HYPE/USD",     "display": "HYPE",     "ordermin": 0.1,      "costmin": 0.5},
    {"rest": "PAXGUSD",     "wsname": "PAXG/USD",     "ws": "PAXG/USD",     "display": "PAXG",     "ordermin": 0.001,    "costmin": 0.5},
    {"rest": "NEARUSD",     "wsname": "NEAR/USD",     "ws": "NEAR/USD",     "display": "NEAR",     "ordermin": 4,        "costmin": 0.5},
    {"rest": "PENGUUSD",    "wsname": "PENGU/USD",    "ws": "PENGU/USD",    "display": "PENGU",    "ordermin": 700,      "costmin": 0.5},
    {"rest": "RENDERUSD",   "wsname": "RENDER/USD",   "ws": "RENDER/USD",   "display": "RENDER",   "ordermin": 2.5,      "costmin": 0.5},
    {"rest": "WLDUSD",      "wsname": "WLD/USD",      "ws": "WLD/USD",      "display": "WLD",      "ordermin": 11,       "costmin": 0.5},
    {"rest": "XXLMZUSD",    "wsname": "XLM/USD",      "ws": "XLM/USD",      "display": "XLM",      "ordermin": 30,       "costmin": 0.5},
]
# --- Scoring ---
MIN_RATIO = 5 / 7          # F3: required = max(2, round(MIN_RATIO * achievable))
STRICT_SEVEN = False       # True -> fixed 5-of-7 regardless of achievable
DOWN_WEEKS = 3             # F1: consecutive lower closes required before an up close
PIVOT_MIN_DEPTH = 0.015    # F2: divergence pivot prominence (1.5%)
# F3: bars sig3 needs before the weekly MACD histogram is evidence at all. calc_macd
# seeds macd_line at slow-1 (25) but the signal line only at slow-1 + signal-1 (33),
# while histogram = macd_line - sig_line spans the WHOLE array — so below the seam
# the histogram is just macd_line, a large bogus negative. sig3 reads an 8-bar
# window, so the whole window must clear the seam, not merely the last bar: at 34
# bars the signal line is seeded yet w_hist[-8:] still covers indices 26-33 and the
# jump from artifact to first real value reads as a crossup. Hence + lookback - 1,
# which is why the observed spurious-fire zone was 26-41.
# Matches the engine's hardcoded calc_macd(wc, 12, 26, 9).
MACD_SEED_BARS = 34        # = (26 - 1) + (9 - 1) + 1: first bar with a real signal line
MACD_LOOKBACK = 8          # sig3's crossup window (w_hist[-MACD_LOOKBACK:])
MACD_MIN_BARS = MACD_SEED_BARS + MACD_LOOKBACK - 1      # 41

# --- Freshness / regime ---
STALE_SECS = 180           # F5: tick_age beyond this -> STALE, alerts suppressed
DANGER_DRSI = 30           # §8: danger tag + tier boundary alignment

# --- Alerting ---
# OPERATOR OVERRIDE: F10 cooldown OFF ("no blockers"). 0 makes should_alert()
# always true (now-last >= 0), so a confirmed BUY re-alerts AND re-places a live
# order on every daily/weekly close while it stays BUY — full pyramid/stacking on
# the same symbol (there is no separate dedupe; rails are also off). Set >0 to
# re-arm the per-symbol wait (e.g. 24 = the old once-a-day guard).
REALERT_HOURS = 0          # F10: per-symbol cooldown before re-alert (0 = disabled)
# COUPLING (audit F2): flipping this >0 re-arms the cooldown, but two strands must
# be fixed IN THE SAME change or it's porous exactly when it matters:
#  1. TOCTOU — the check (last_alert_ts) runs on the writer while the insert
#     (alerter.fire) runs in the offloaded dispatch thread, so two near-simultaneous
#     closes both pass. Make check+insert atomic on the writer.
#  2. The alerts table IS the cooldown ledger, but _dispatch now places the order
#     BEFORE alerter.fire and isolates the alert — so a failed alert records NO fire
#     for an order that DID happen, blinding the cooldown to it. When re-enabling,
#     record the fire on the ORDER path (not the decoration path), so the ledger
#     reflects orders placed, not alerts that happened to succeed.
PROVISIONAL_ALERTS = False # invariant 7: provisional is display-only unless True

# --- Conviction multipliers (F8): score relative to required threshold ---
CONVICTION = {0: 1.0, 1: 2.0, 2: 3.0}  # +1 -> 2x, +2 and above -> 3x (STARTER at 0)

# --- Named horizontal price levels (F7), display-only, operator-edited ---
LEVELS = {
    "BTC/USD": [("62.8k", 62858), ("57.6k", 57585)],
}

# --- UI cadence ---
SIMPLE_SECS = 60           # plaintext frame period in --simple mode
RENDER_HZ = 2              # rich Live render cap
FLASH_SECS = 0.6           # tick-direction tint window; >= one render period at
                           # RENDER_HZ=2 so the flash is actually visible (spec's
                           # ~300ms would fall between frames half the time)

# --- Candle-close clock fallback (SPEC §5b) ---
# The WS ohlc feed sends NOTHING across an interval border until the next trade.
# The clock watchdog detects a forming bar past its deadline (+grace), REST-
# confirms the closed bar, flips it, and triggers the confirmed recompute.
CLOSE_GRACE_SECS = 5
CLOSE_POLL_SECS = 15

# --- REST throttle (Appendix B) ---
MIN_CALL_GAP = 0.6
FETCH_RETRIES = 2

# --- Telegram: env only, never in files, never committed (§10/§11) ---
TG_TOKEN = os.environ.get("ORACLE_TG_TOKEN")
TG_CHAT = os.environ.get("ORACLE_TG_CHAT")

# ═══════════════════════════════════════════════════════════════════════════
# EXECUTION — live Kraken spot-margin (operator override, docs/RULINGS.md).
# Deterministic: signal fires -> size -> open leveraged long -> rest stop -> log.
# NO learning brain. Off by default; nothing can fire until EXEC_MODE flips.
# ═══════════════════════════════════════════════════════════════════════════
# EXEC_MODE is fail-CLOSED: only the EXACT canonical strings arm anything. Any other
# value — a case slip ('LIVE'), a trailing space ('paper ', trivial in .env/systemd),
# or a safe-sounding typo ('test'/'sim'/'dry') — resolves to 'off' with a loud error.
# We deliberately do NOT lower()/strip()-coerce: coercing 'LIVE'->'live' would arm real
# money on a typo. Every downstream gate is a BLOCKLIST (mode=='off' returns early, else
# the code falls THROUGH to the live AddOrder path), and poll_fills/verify_open_stops are
# gated on exact 'live' — so an unrecognized mode that slipped past would place real
# leveraged orders that never get a protective stop or fill-reconcile. Catch it here.
_VALID_EXEC_MODES = ("off", "paper", "validate", "live")


def _normalize_exec_mode(raw):
    if raw in _VALID_EXEC_MODES:
        return raw
    _log.error("DEEPFIELD_EXEC_MODE=%r is not one of %s — refusing to arm; running OFF.",
               raw, _VALID_EXEC_MODES)
    return "off"


EXEC_MODE = _normalize_exec_mode(os.environ.get("DEEPFIELD_EXEC_MODE", "off"))   # off | paper | validate | live

# Web console — served in-process by the live bot (a daemon thread) so the one
# desktop launch brings up TUI + web together. Read-only; set DEEPFIELD_WEB=0 to
# disable. The desktop launcher opens the browser to this port.
WEB_ENABLED = os.environ.get("DEEPFIELD_WEB", "1") != "0"
WEB_PORT = int(os.environ.get("DEEPFIELD_WEB_PORT", "8787"))

# Sizing. "min" (default, for now): buy the MINIMUM order per pair — positions so
# small nothing meaningful is ever at risk, so liquidation is a non-issue. "risk":
# 2% of equity off the stop (kept for later; revisit stop-vs-liquidation first).
EXEC_SIZE_MODE = os.environ.get("DEEPFIELD_EXEC_SIZE", "min")   # min | risk
RISK_PCT = 0.02
# Equity used for sizing math in paper/off, and the simulated exchange's STARTING
# CASH (paper_broker). Env-overridable because it silently sets how long a paper run
# takes to become REPRESENTATIVE: position sizes floor to the exchange minimum and
# the respend governor accrues new notional at an absolute $5/hr, so neither scales
# with equity — only the RISK ratios do. At $1000 a paper book needs ~$4.4k of
# notional (~37 days) to reach the live book's ~226% margin level, and until then
# the rails, reverse gear and stress panel cannot fire at all. Starting near the
# live book's equity (~$180) reaches that regime in ~7 days instead. Takes effect
# on a FRESH simulated book only — cash is seeded once, so an existing paper DB
# keeps the balance it started with.
def _paper_equity(raw, default=1000.0):
    """Fail SAFE, like _normalize_exec_mode above: a typo in an env var must never
    stop the bot from starting. A bare float() here raises at import time, which
    would take the whole process down before logging exists to say why."""
    try:
        v = float(raw)
    except (TypeError, ValueError):
        _log.error("DEEPFIELD_PAPER_EQUITY=%r is not a number — using $%.0f", raw, default)
        return default
    if v <= 0:
        _log.error("DEEPFIELD_PAPER_EQUITY=%r must be positive — using $%.0f", raw, default)
        return default
    return v


PAPER_PORTFOLIO_USD = _paper_equity(os.environ.get("DEEPFIELD_PAPER_EQUITY", 1000.0))

# ── simulated exchange (paper mode; see deepfield/paper_broker.py) ───────────
# Costs the paper book must carry, or paper reads rosier than live and every
# conclusion drawn from it is wrong in the same direction.
PAPER_FEE_MAKER_PCT = 0.0002        # 0.02% — resting post-only entries/harvest closes
PAPER_FEE_TAKER_PCT = 0.0005        # 0.05% — stop-loss MARKET exits take liquidity
PAPER_SLIPPAGE_PCT = 0.0005         # 5bp worse than the trigger on a stop-market fill
# Kraken bills margin rollover every 4h. 0.015% per 4h = 0.09%/day = ~33%/yr on open
# notional, which is what the live book actually measured (~$0.39/day, 2026-07-15) —
# and financing is the single largest cost this strategy carries, so it is modeled.
PAPER_ROLLOVER_SECS = 14400.0
PAPER_ROLLOVER_PCT = 0.00015

# Per-order sanity ceiling (Finding 8): refuse any single order whose NOTIONAL
# (volume x entry — the leveraged position size, i.e. the blast radius) exceeds this.
# NOT a rail: it never halts the bot and never shrinks a valid min-size order (min
# notionals run ~$3-8). It converts "a corrupt `pairs` row or a flipped EXEC_SIZE_MODE
# silently changes the blast radius" into a refused order + a loud log — making
# min-sizing a CHECKED bound, not just a config knob. 0 = disabled; raise it if you
# deliberately move to larger risk-mode sizing.
EXEC_MAX_ORDER_NOTIONAL_USD = 50.0

# Stop: weekly support (bottom-thesis invalidation), clamped to a sane band so a
# razor-thin stop can't blow up position size and a far one can't dust it.
STOP_MODE = "support"               # support | pct
STOP_PCT = 0.10                     # used when STOP_MODE="pct"
STOP_MIN_PCT = 0.05
STOP_MAX_PCT = 0.15
PROTECTIVE_STOP = True              # rest a real stop on the exchange (kill-safe)

ENTRY_ORDERTYPE = "limit"           # post-only maker ONLY (no market entries). A resting
                                    # limit is recorded status='pending' and promoted to
                                    # 'open' only when the fill monitor confirms it filled.
POST_ONLY_SLIP_PCT = 0.001          # bid this far BELOW last so the post-only maker can't
                                    # cross the ask (a crossing post-only is rejected -> silent
                                    # no-fill). 10bps ~= a patient bottom bid; negligible cost.
ENTRY_TTL_SECS = 86400              # cancel a still-unfilled post-only entry bid after this
                                    # long (default 1 day) so stale bids don't pile up against
                                    # Kraken's open-order cap and crowd out protective stops
                                    # (Finding 5). Fills are unaffected (a filled bid is 'open',
                                    # not 'pending'), so stacking still works. 0 = never expire.
# Continuous laddering: when a resting entry FILLS, immediately drop the next rung one
# LADDER_STEP_PCT below the fill (post-only, min-fill, SAME support stop) so accumulation
# continues down toward the stop without waiting for a candle close or a restart. Bounded
# by a NATURAL FLOOR — a rung that would land at/under the stop is not placed — so a full
# descent is ~ (entry-stop)/step rungs (~8 at 1% over an ~8% stop), never a runaway. One
# resting rung per symbol at a time; a gap-down that puts the rung above market is rejected
# by post-only (ladder pauses, safe) until the next fill/close. LIVE mode only.
LADDER_CONTINUOUS = True
LADDER_STEP_PCT = 0.01              # next rung this far below the fill (1% ~= 8 rungs to an 8% stop)
LADDER_STOP_BUFFER = 0.0            # extra margin ABOVE the stop below which no rung is placed
MARGIN_CAP_PCT = 0.90               # a single position may post at most this frac of free margin

# Rung/entry size multiplier (operator 2026-07-13 "bigger rungs, stack as much as
# possible"): every min-mode order — confirmed-BUY entries, ladder rungs, seeds —
# is sized at SIZE_MULT x the min fill; conviction (2x/3x) stacks ON TOP, so a 3x-
# conviction rung at SIZE_MULT=3 is 9x min (~$30-45 notional — still under the
# conviction-scaled EXEC_MAX_ORDER_NOTIONAL ceiling). Fail-safe: an unparseable
# env override runs at 1x (min), never at a surprise size.
# 2026-07-15: default raised 3 -> 16 (operator "squeeze more profit"). At 1656%
# margin-level the book was ~6% deployed (~$115 notional on $181 equity); 16x
# targets margin-level ~350% (~$520 notional, still a 4.4x buffer over the 120%
# stack floor). Env still overrides. The ceiling scales with SIZE_MULT so no clamp.
try:
    SIZE_MULT = max(1.0, float(os.environ.get("DEEPFIELD_SIZE_MULT", "2")))  # 2026-07-31: 1->2, operator — the 07-29 stop-ratchet's pre-registered revisit condition (post-ratchet proved-rung hit rate >70%) measured 90% (18 rungs harvested at +4% vs 2 stopped at breakeven since 07-29); the landscape differs from the 8x/16x era: respend governor paces all new-growth notional at $5/hr regardless of this knob, reverse gear + rails armed. Prior: 2026-07-24: 2->1 (min-size buys "for a while"), operator, alongside the second per-pair trim. The 07-22 trim restored ML 119->250% and the ladder spent the whole cushion inside 24h (ML back to 110-120%, free margin $32, 47 -> 103 lots) — 2x-min rungs across a 29-pair universe out-accumulate what the 200% stack floor can hold back, because the floor only gates NEW seeds, it never unwinds. 1x is the floor of this knob (max(1.0, ...)); the next lever down is the pair universe, not this. Prior: 3->2 on 07-20, operator (existing book untouched, plays out at 2x-min from here). Prior: 2->3 on 07-19. At the time of the change the book sat at 0.44x effective leverage against a measured 4.22x survivable ceiling — a tenth of the limit — so 3x only changes the PACE of accumulation, not where it ends. The ceiling is enforced by MARGIN_LEVEL_STACK_FLOOR_PCT (raised 160->200 in the same change), NOT by this multiplier. (History: 16->8 on 07-16 after the $1,484/9x/ML-106% near-call; 8->2 on 07-19 after the T/P flatten.)
except ValueError:
    _log.error("DEEPFIELD_SIZE_MULT=%r is not a number — running at 1x (min size)",
               os.environ.get("DEEPFIELD_SIZE_MULT"))
    SIZE_MULT = 1.0

# Seeded chains: every seed pair keeps a ladder chain WORKING at all times — a
# pair with no open rows and no resting bid gets a post-only starter bid just
# below live, NOT gated on a confirmed BUY (the backtest showed the signal is
# beta; the ladder is the strategy). Empty tuple disables seeding.
# ALL pairs are seed pairs (operator dispatch 2026-07-19: "always-on ladders,
# no signal gate" across the entire margin universe — min-fill rungs; the
# margin cost of the lower-leverage tiers is operator-accepted). Regime gate,
# HALT, stack floor and all rung guards still apply per placement.
# USDC/USD is a PEGGED pair: 731 daily bars close 0.9995–1.0001 — the +4% rung
# harvest can never print, the 5%-minimum stop can never trigger, and a filled
# lot would pay rollover forever for zero expected move. Seeding it only cycles
# a structurally-unfillable ~$5 bid through the respend bucket (bids rest 0.1%
# below a peg that doesn't dip; 7 lifetime bids, 7 TTL cancels, 0 fills).
# Pulled from seeding 2026-07-30 — this reverses one line of the 07-19
# full-universe dispatch; restore by deleting the exclusion. Stays in PAIRS:
# display and signals untouched.
SEED_PAIRS = tuple(p["ws"] for p in PAIRS if p["ws"] != "USDC/USD")

# Equity take-profit (operator 2026-07-13 "t/p out at +20%, then go again"): when
# live equity >= tp_baseline * (1 + TP_PCT), flatten the WHOLE book — cancel every
# resting bid and protective stop, close each pair's live open volume — then reset
# the baseline to post-flatten equity and let the seeder restack: a compounding
# stack->harvest->restack cycle, recorded per-cycle in the tp_cycles ledger.
# Closes are POST-ONLY LIMIT sells pegged a tick over best bid, re-pegged each
# poll pass until flat (operator 2026-07-21 — market closes paid taker fees +
# spread; the long-only rule is amended again: a T/P close may REST until filled,
# tracked in orders.close_txid and owned exclusively by the flatten). The
# tp_baseline is DEPOSIT-SHIFTED (app._poll_external_flows): net USD deposits/
# withdrawals detected on the Ledgers API move the baseline the same amount, so
# +TP_PCT always measures TRADING profit, never money walking in the door.
# The TARGET is TROUGH-RATCHETED (operator 2026-07-24): meta['tp_trough'] tracks
# the equity low since arm and the flatten fires at min(baseline, trough) *
# (1+TP_PCT), so a drawdown can never park the target out of reach while fees
# bleed. The baseline itself never ratchets — the tp_cycles ledger books profit
# against it.
# FLOORED AT BASELINE (operator 2026-07-27, TP_TARGET_FLOOR_BASELINE): the ratchet
# may lower the target toward a bounce off the low but NEVER below baseline, so a
# fire can never bank a loss (worst case is breakeven). This closes the red-cycle
# the 07-27 audit found (Jul-26 fired off a trough 21% under baseline, locking
# -$15.09). Tradeoff: the book no longer auto-flattens OUT of a deep drawdown at a
# loss — it HOLDS (per-lot stops still protect every position) until equity
# recovers to baseline. Set False for the old min(baseline,trough) behavior.
TP_ENABLED = True
TP_PCT = 0.20
TP_TARGET_FLOOR_BASELINE = True

# Per-RUNG take-profit harvest (operator 2026-07-29 "build it at 4%"): each open
# lot banks itself at entry*(1+TP_RUNG_PCT) instead of waiting for the whole-book
# equity target above (which stays armed as the melt-up backstop). Backtest over
# the 446 live rungs 07-13..07-28: realized net peaks at 4% (+$45, 69% win rate,
# median 1.5 days fill->bank); 20% per-rung fired 7 times in 446. The trigger
# rides the poll cycle off the LOCAL candle price (no API cost when nothing is
# near target); the exit is the flatten's maker mechanics: cancel the rung's stop
# FIRST, then rest a post-only limit sell a tick over best bid — the stop and the
# harvest sell NEVER rest together (double-sell -> short), tracked in
# orders.close_txid exactly like a flatten close so reprotect/reconcile leave it
# alone. If the market sags below entry*(1+TP_RUNG_FLOOR_PCT) before the sell
# fills, the harvest ABORTS: sell canceled, stop re-armed (reprotect path) — the
# chase may follow a rip down to the floor but never banks below it, so a
# harvest can never realize a loss (floor > round-trip fees). Same long-only
# amendment as the flatten: an event-triggered close of a long, resting until
# filled. One harvest per pair at a time; new starts capped per pass (API budget).
TP_RUNG_ENABLED = True
TP_RUNG_PCT = 0.04
TP_RUNG_FLOOR_PCT = 0.02
TP_RUNG_MAX_PER_PASS = 4

# Stop RATCHET on a proved rung (operator 2026-07-29, off the same night's audit).
# The harvest layer is geometrically asymmetric: +4% up against a 7.83% mean stop
# distance (volume-weighted across the live book), so net of round-trip fees it
# needs ~70% of rungs to reach target before stop merely to break even — and the
# 446-rung backtest measured 69%. The layer sits ON its break-even line, and the
# leak is one-sided: a rung that reaches +4%, rests its sell, then fades under the
# floor ABORTS and re-arms its stop at the ORIGINAL invalidation level, riding a
# further ~8% down having already proved it could pay. Pin that stop up to
# entry*(1+TP_RUNG_RATCHET_PCT) at the moment the harvest starts, so a proved
# rung's worst case is ~breakeven (fees) instead of a full stop-out. This lowers
# the break-even hit rate well under 70% without touching leverage, size, or the
# long-only rule (a stop is still the only thing that sells).
# Written to orders.stop_prot, NOT `stop` — see the store.py schema note: `stop`
# is the ladder's inherited invalidation level, and ratcheting it in place would
# trip the "rung would hit stop, ladder floor reached" guard and freeze
# accumulation on the winning pairs. 0.0 = breakeven. Keep BELOW
# TP_RUNG_FLOOR_PCT: the ratchet is applied while the bid is above the floor, and
# a stop resting at/above the market fires on contact — also enforced per-rung
# against the live bid, so a misconfigured value here can only no-op, never fire.
TP_RUNG_RATCHET_ENABLED = True
TP_RUNG_RATCHET_PCT = 0.0

# Runtime exchange-truth sweep (audit 2026-07-13 #1): re-run the startup ledger↔Kraken
# reconcile (verify_open_stops) every this-many seconds from the poll cycle, so an
# intraday stop-fire, force-liquidation, or manual close is noticed within minutes —
# not at the next restart. Costs ~4 private API calls per pass at the current book.
# 0 disables (restores boot-only reconcile). NOT a rail: it only trues the ledger up
# to the exchange and cancels provably-orphaned stops; it never blocks an entry.
RUNTIME_RECON_SECS = 900

# Adoption of untracked exchange volume. Reconcile has always DETECTED open volume no
# ledger row tracks (manual position, another system) and shouted about it — but never
# protected it, so it sat naked until someone noticed by hand (operator's manual
# HYPE/NEAR buys, 2026-07-22: ~7h unstopped through a restart). Adoption gives it a
# ledger row so the normal protect path rests a stop over it.
# The grace window is the safety: volume this bot itself just filled must be claimed by
# the userref/fill recovery, NOT adopted here, or one position ends up with two rows and
# two stops. Any 'pending' row on the symbol blocks adoption outright; otherwise the
# surplus must sit stable and unclaimed this long (>= one further reconcile) first.
ADOPT_UNTRACKED = True
ADOPT_GRACE_SECS = 1800

# Margin-level watch (audit 2026-07-13 #2). Kraken margin-calls at ml<=80% and force-
# liquidates from ml<=40% — bypassing every stop, invisibly to the ledger. This is
# protection against the EXCHANGE seizing the book, not a self-brake:
#  - below MARGIN_LEVEL_ALERT_PCT: fire a (throttled) safety alert. Alert only, never
#    gates an order. Read by app._check_margin_level.
#  - below MARGIN_LEVEL_STACK_FLOOR_PCT: pause SEEDS and LADDER RUNGS only — confirmed-BUY
#    signal entries are NEVER gated by this (operator no-blockers stance). FAILS OPEN:
#    a stale/unknown margin level never pauses anything.
# 0 disables either threshold.
# 2026-07-22: 150 -> 120, and WIRED. It sat at 150 unread by any code since the audit
# wrote it, so the number was never pressure-tested against a real book. 150 was the
# ratio twin of an all-pairs-10:1 stack; at the current 2-5x per-pair mix the book
# floors near ml 130 in ordinary running (p05 136, p50 161, max 199 over the last 3000
# logged samples) while the price-space liq buffer reads a healthy 21.9% NOMINAL — the
# two metrics genuinely diverge, which is why this watch exists separately and why its
# threshold cannot be copied from the buffer tiers. Wiring 150 verbatim would have paged
# through normal operation and burned the channel (cf. the 531-events-in-24h finding
# behind the edge-triggered stack-pause narration). 120 clears the observed operating
# floor and still sits above the 2026-07-16 near-margin-call band (ml 106-115), so it
# stays silent until something real is happening. 0 disables.
MARGIN_LEVEL_ALERT_PCT = 120
# 2026-07-19: raised 160->200 (operator). The book OPERATES AT THIS FLOOR, so this
# number — not SIZE_MULT — is what actually caps leverage. At all-10:1, ml 160 permits
# L_eff 6.25x and a 12% liq buffer; measured over 2y the worst 1-day adverse basket
# move is 16.76% universe-wide and 19.67% for the pairs actually held, so the old
# floor allowed a book that a repeat of an ALREADY-OBSERVED day takes through
# liquidation. ml 200 -> L_eff 5.0x, 16% buffer. (Full enforcement of the 4.22x
# survivable ceiling would need ml ~237; 200 is the operator's chosen midpoint
# between cushion and deployment.) Caveat kept honest: stops sit ~8-15% below entry
# and fire first, so the liq buffer is the BACKSTOP for gap-through risk, not the
# primary defense. Prior: 2026-07-16 raised 120->160 after a drop compressed ml to
# 106% (7% from trouble). See deepfield/backtest_ladder.py and STRESS_* below.
MARGIN_LEVEL_STACK_FLOOR_PCT = 200

# ── Respend governor (respend-RATE throttle) ────────────────────────────────
# The stack floor above is a BINARY gate: below it seeds/rungs hard-pause, above
# it they redeploy at full cadence. That cliff is why a fresh T/P cushion (a
# flatten leaves ml ~400%+) re-levers straight back to the 200% floor within
# ~24-48h — banked profit is immediately re-risked instead of compounding. This
# meters NEW book-growth notional (SEEDS + LADDER RUNGS only) with a leaky
# bucket: at most RESPEND_BUDGET_USD_PER_HR of new notional deploys per hour,
# the bucket capped at RESPEND_BURST_USD (the immediate post-flatten wave, then
# it meters). It NEVER touches confirmed-BUY signal entries (they bypass, same
# as the floor), NEVER touches leverage, NEVER touches stops. Below the floor
# still hard-pauses underneath this. FAILS OPEN on any unreadable state.
# 0 = OFF (default; this is a brake — operator no-blockers stance, arm to taste).
# Starting calibration for a ~$375-notional book: PER_HR ~5, BURST ~40 → full
# re-lever takes ~3 days instead of ~1. Watch the ml curve after a T/P and tune
# the one number.
RESPEND_BUDGET_USD_PER_HR = 5.0
RESPEND_BURST_USD         = 40.0

# Defense buffer engine (audit Wave 1, DEEPFIELD_AUDIT_EVIDENCE.md §B/§G). The
# ml floor above is a ratio; the DEFENSE tiers below are the SAME comfort zone
# expressed in PRICE space — the adverse basket move (%) that would drop the
# account to Kraken's ml=40% force-liquidation line. With all pairs at 10:1,
# ml 160 ≡ a 12% liq buffer and ml 200 ≡ a 16% one.
#
# NOTE (2026-07-19): NOMINAL=12 was written as the price-space TWIN of the ml-160
# floor. The floor moved to 200 (≡16%) and this deliberately did NOT follow, so the
# two are no longer the same line: growth pauses at a 16% buffer while the tier
# still reads NOMINAL down to 12%. That dead band is intentional — raising NOMINAL
# would re-tier the alert stream, and REVERSE_GEAR_TARGET_PCT=12 (an actuator that
# SELLS) is calibrated against this same 12, so moving it is a risk decision in its
# own right rather than a knock-on edit. Consequence to know: after a reverse-gear
# trim the book rests at a 12% buffer (L_eff 6.25x) and simply cannot grow again
# until it recovers to 16% — conservative, not contradictory.
# Tiers on buffer_liq_pct:  NOMINAL >= 12 > CAUTION >= 6 > CRITICAL.
# TELEMETRY/ALERTING ONLY — deepfield.defense never gates or sizes an order.
DEFENSE_BUFFER_NOMINAL_PCT = 12.0   # price-space twin of ml-160 (see NOTE above)
DEFENSE_BUFFER_CRITICAL_PCT = 6.0   # < this liq buffer pages an escalated 'liq-risk' alert

# --- Intraday stress telemetry (2026-07-19) -------------------------------------
# buffer_liq_pct is denominated in ADVERSE BASKET MOVE, so the honest question is
# "how big a basket move actually happens?" Measured over 2y of daily bars on 20
# live pairs: worst 1-day -16.76%, worst 5-day -23.17%, with mean pairwise
# correlation 0.60 — a single-beta basket whose tail is common, not idiosyncratic.
# Against that, buffer = 1/L_eff - 0.40*m/v says a book at 5x per-pair leverage
# only survives the worst observed DAY below ~4.0x effective, and the worst 5-DAY
# stretch below ~3.2x. The book ran 9x into a 3.1% buffer twice.
#
# These are TELEMETRY thresholds, not brakes: crossing them journals and alerts,
# and never blocks, sizes or cancels an order. The reverse gear (below) remains the
# only actuator. Sourced from the DAILY series so the reference move is a real
# historical basket move, refreshed as history grows rather than frozen here.
STRESS_ENABLED = True
STRESS_POLL_SECS = 300              # own cadence; well off the ~8s exec loop
STRESS_INTRADAY_LOOKBACK_BARS = 96  # 96 x 15m == last 24h of intraday structure
STRESS_REFERENCE_DAYS = 730         # daily-bar window the reference move is drawn from
STRESS_REFERENCE_HORIZONS = (1, 5)  # measure worst 1-day and 5-day basket moves
# Alert when live eff_leverage exceeds the ceiling that survives the worst observed
# 1-day basket move. Multiplier gives a little headroom before paging.
STRESS_LEVERAGE_ALERT_RATIO = 1.0

# ── Reverse gear (audit Wave 4): the DELEVERAGE GOVERNOR ─────────────────────
# The account had an accelerator (stacking) and a brake (the ml floor pausing new
# rungs) but NO reverse gear — when the book got too big for its cash, the only way
# out was price rising, stops firing, or the operator wiring a deposit (2026-07-16,
# at a 4.4% funding fee). This closes that gap: when the price-space liq buffer
# decays below TRIGGER, the bot sheds whole fill-lots (largest-notional first) until
# the buffer recovers to TARGET, then stops. The closes are EVENT-TRIGGERED market
# orders sized to live open long volume (capped at net long — can never flip short),
# exactly like the T/P flatten; NEVER a resting sell (long-only rule intact).
#
# Per-LOT by design (the 2026-07-16 out-of-band trim incident): it closes whole DB
# rows — cancel that lot's stop, market-close its volume, retire the row — so it can
# never oversize a stop (flip risk) or leave a partial position naked. It also cancels
# resting entry bids on fire, so a bid can't refill and re-lever mid-deleverage (the
# other failure seen that day). FAIL-OPEN: an unknown/None/flat buffer never trims.
# Capped per pass so a single bad read can't flatten the book.
#
# ARMED (operator-enabled 2026-07-16, after the near-margin-call + manual deleverage):
# this actuator autonomously SELLS to deleverage when the liq buffer decays below
# TRIGGER. Default ON so it survives a desktop relaunch; set DEEPFIELD_REVERSE_GEAR=0
# (env) to disable without a code edit. Dormant unless the buffer is actually < TRIGGER.
REVERSE_GEAR_ENABLED = os.environ.get("DEEPFIELD_REVERSE_GEAR", "1") != "0"
REVERSE_GEAR_TRIGGER_PCT = 8.0      # fire when liq buffer < this (lower CAUTION band, above CRITICAL 6)
# 2026-07-19: target 12 -> 16 (operator), to land on the ml-200 stack floor rather
# than the retired ml-160 one. Previously the gear trimmed to 12% and the floor then
# refused to grow below 16%, so a fired gear left the book parked in a dead band it
# could not trade out of. Landing ON the floor means post-trim the book is
# immediately allowed to accumulate again.
#
# This makes the gear sell HARDER, which is the real cost of the change. At all-10:1,
# firing at an 8% buffer means L_eff 8.33x; recovering to 12% sheds ~25% of notional,
# recovering to 16% sheds ~40% — roughly 60% more closed per event, and every close
# crystallises loss plus fees (the 2026-07-16 manual trim cost ~$12.33 + $3.44). The
# trigger deliberately stays at 8: when to act is an emergency question, how far to
# correct is a coherence one, and only the latter changed. MAX_LOTS_PER_PASS still
# caps each pass, so a deeper target simply takes more passes rather than one big
# flatten.
REVERSE_GEAR_TARGET_PCT = 16.0      # trim until liq buffer >= this (== the ml-200 floor)
REVERSE_GEAR_MAX_LOTS_PER_PASS = 4  # cap lots closed per poll pass; re-evaluates next cycle (bad read can't flatten)
REVERSE_GEAR_CANCEL_BIDS = True     # cancel resting entry bids on fire so they can't re-lever mid-trim

# Safety-alert channel (audit 2026-07-13 #3): sound + notify-send (+ Telegram iff the
# env vars are set) for money-path safety events — UNPROTECTED positions, reconcile
# mismatches, margin-level danger, T/P cycle events. Throttled per event-kind so a
# retry loop can't turn the speaker into a siren. 0 disables throttling (every event).
SAFETY_ALERT_THROTTLE_SECS = 1800

# 2026-07-24 (operator: "calm the notify-send alerts down, they are annoying"). The
# channel was routing EVENTS and STATES identically: every kind got a `-u critical`
# popup plus a sound. A state that persists (margin level under the floor) then re-paged
# on a repeat timer all night — worse, the ml bucket key is per-5-points, so a level
# wobbling across a boundary (110 <-> 115 overnight on 07-23) alternated two throttle
# keys and paged at ~half the nominal window. Nothing was wrong that a popup could fix:
# the operator watches the console 24/7 ([[no-alerting-suggestions]]), so a chronic
# state belongs in the log + journal + dashboard, not in the speaker.
# QUIET kinds still log at WARNING and still journal — they just don't make noise or
# raise a popup. Anything a human must act on RIGHT NOW (a naked leveraged long, a
# fired stop, a ledger/exchange mismatch) stays loud and is deliberately not listed.
SAFETY_ALERT_QUIET_KINDS = ("margin-level", "trim", "tp")
SAFETY_ALERT_QUIET_THROTTLE_SECS = 21600   # 6h; log-only, so a long window costs nothing

# margin-level escapes the quiet list and goes loud below this — the alert floor (120)
# is "getting tight", which is a dashboard fact; THIS is "the exchange is about to take
# the book", which is a wake-the-operator fact. Kraken calls at 80% / liquidates from
# 40%, and the 2026-07-16 near-margin-call ran 106-115%, so 100 sits below routine
# tightness and above the band where it stops being recoverable. 0 = never escalate.
MARGIN_LEVEL_LOUD_PCT = 100

# Re-arm hysteresis for the worsening-slide ratchet. Recovering to EXACTLY the alert
# floor must not re-arm the watch: the 07-23 overnight wobble ran 110 <-> 120 against a
# floor of 120, so a bare floor crossing would re-arm and re-page on the very next dip —
# the ratchet would have been decorative. Require a real recovery (1.15x floor = ml 138)
# before the same slide counts as news again.
MARGIN_LEVEL_REARM_RATIO = 1.15

# Rollover-fee accounting (audit 2026-07-13 #2): Kraken charges 0.01-0.05% of notional
# per 4h to hold a margin position. Poll the Ledgers API for rollover/margin entries
# at this cadence and accumulate the paid fees into meta (fees_total / fees_day) so
# the drag is VISIBLE next to realized P&L instead of silently mimicking market losses.
# Display/accounting only — never gates an order. 0 disables the poll.
ROLLOVER_POLL_SECS = 3600

# FORK A regime gate: accumulate in weakness, not strength. When True, new confirmed
# entries AND ladder rungs are placed ONLY when the BTC regime is not confirmed BULL
# ("stop adding once BULL" — buy the fall/turn, not the strength). FAILS OPEN: an
# unknown/missing/other regime (BEAR/RECOVERY/NEUTRAL/UNKNOWN) still accumulates, so a
# stale or unavailable regime can never silently halt entries (operator no-blockers
# stance). Only the unambiguous BULL state pauses accumulation. Set False to disable.
ACCUMULATE_ONLY_IN_BEAR = True
NO_ACCUMULATE_REGIMES = ("BULL",)   # regimes that pause new entries/rungs when the gate is on
# NOTE: the strategy is LONG ONLY — a resting sell can net short (Kraken spot-margin has
# no reduce_only). The only sells are protective STOPS (sized to close a long) and the
# TP_ENABLED equity flatten above (event-triggered market closes sized to live open
# volume at that instant, operator-ordered 2026-07-13). Do NOT add resting sells.

# Risk rails (deterministic hard limits, from GoldenEye — NOT learners).
# RE-ARMED 2026-07-30 at operator direction ("no more off the rails — do it your
# way"), recalibrated for the ladder era in the same change — the 07-04 values
# predate continuous laddering:
#   MAX_OPEN_POSITIONS 15 -> 300. rails_ok counts COMMITTED rows (open + pending);
#   the 29-pair ladder book runs ~90 open + ~25 resting bids in normal shape, so 15
#   was a permanent freeze (and, via rails_ok's short-circuit, made every check
#   behind it unreachable). 300 ≈ 10-rung chains on every pair — a runaway-loop
#   backstop, never a working-set cap. The working-set brakes are the ML stack
#   floor, the respend governor, and the L_eff ceiling gate in _stack_margin_ok.
#   KILL_SWITCH peak: peak_equity now RESETS at each T/P cycle settle
#   (executor._check_take_profit) and SHIFTS with external deposits/withdrawals
#   (app._poll_external_flows), so the 20% drawdown measures TRADING loss of the
#   CURRENT cycle — the old never-resetting, deposit-contaminated peak sat 3.4%
#   above 2026-07-30 equity and would have latched on the first red day.
# The manual HALT file (below) stays the operator's hand-on-switch, and the
# per-position protective stop is the strategy's own exit — neither is a
# circuit breaker.
RAILS_ENABLED = True
MAX_OPEN_POSITIONS = 300
DAILY_LOSS_LIMIT_USD = 15.0         # halt new entries after this realized daily loss
WEEKLY_LOSS_LIMIT_USD = 35.0
KILL_SWITCH_DD_PCT = 0.20           # halt at 20% drawdown from peak equity (manual reset)
HALT_FILE = os.path.join(PROJECT_ROOT, "deepfield.HALT_ENTRIES")  # touch to halt / rm to resume

# Per-pair leverage — a FIXED hardcoded value Kraken must accept verbatim (it must
# be present in the pair's leverage_buy array). Sent exactly as-is on every order,
# hydra-style. Verified 2026-07-04 == max Kraken leverage_buy per pair. HARDCODED TO
# THE PER-PAIR MAX ON PURPOSE — do NOT lower. (The fork-A 2x de-lever was a mistake and
# was reverted 2026-07-11 at operator direction.)
PER_PAIR_LEVERAGE = {
    "BTC/USD": 10,
    "ETH/USD": 10,
    "XRP/USD": 10,
    "SOL/USD": 10,
    "SUI/USD": 10,
    "DOGE/USD": 10,
    "LTC/USD": 10,
    "LINK/USD": 10,
    "ADA/USD": 10,
    "AVAX/USD": 10,
    "AAVE/USD": 5,
    "UNI/USD": 5,
    "DOT/USD": 5,
    "BCH/USD": 5,
    "ALGO/USD": 2,
    "CRV/USD": 5,
    "HBAR/USD": 5,
    "PEPE/USD": 5,
    "SHIB/USD": 5,
    "TRX/USD": 5,
    "ZEC/USD": 5,
    "USDC/USD": 10,
    "HYPE/USD": 5,
    "PAXG/USD": 5,
    "NEAR/USD": 3,
    "PENGU/USD": 3,
    "RENDER/USD": 3,
    "WLD/USD": 3,
    "XLM/USD": 2,
}
# Leveraged orders MUST use the :BTNL margin-book name (Non-ECP rejects spot name).
MARGIN_PAIR = {
    "BTC/USD": "XBTUSD:BTNL",
    "ETH/USD": "ETHUSD:BTNL",
    "XRP/USD": "XRPUSD:BTNL",
    "SOL/USD": "SOLUSD:BTNL",
    "SUI/USD": "SUIUSD:BTNL",
    "DOGE/USD": "XDGUSD:BTNL",
    "LTC/USD": "LTCUSD:BTNL",
    "LINK/USD": "LINKUSD:BTNL",
    "ADA/USD": "ADAUSD:BTNL",
    "AVAX/USD": "AVAXUSD:BTNL",
    "AAVE/USD": "AAVEUSD:BTNL",
    "UNI/USD": "UNIUSD:BTNL",
    "DOT/USD": "DOTUSD:BTNL",
    "BCH/USD": "BCHUSD:BTNL",
    "ALGO/USD": "ALGOUSD:BTNL",
    "CRV/USD": "CRVUSD:BTNL",
    "HBAR/USD": "HBARUSD:BTNL",
    "PEPE/USD": "PEPEUSD:BTNL",
    "SHIB/USD": "SHIBUSD:BTNL",
    "TRX/USD": "TRXUSD:BTNL",
    "ZEC/USD": "ZECUSD:BTNL",
    "USDC/USD": "USDCUSD:BTNL",
    "HYPE/USD": "HYPEUSD:BTNL",
    "PAXG/USD": "PAXGUSD:BTNL",
    "NEAR/USD": "NEARUSD:BTNL",
    "PENGU/USD": "PENGUUSD:BTNL",
    "RENDER/USD": "RENDERUSD:BTNL",
    "WLD/USD": "WLDUSD:BTNL",
    "XLM/USD": "XLMUSD:BTNL",
}
# :BTNL margin-book PRICE precision (differs from spot — too many decimals rejects).
MARGIN_TICK_DECIMALS = {
    # Incumbent 21: probe-verified 2026-07-13 (CRV/SHIB coarser than spot).
    # New pairs: spot pair_decimals as the starting guess — --exec-probe
    # auto-coarsens to the :BTNL book's accepted precision (the authority).
    "BTC/USD": 1,
    "ETH/USD": 2,
    "XRP/USD": 5,
    "SOL/USD": 2,
    "SUI/USD": 4,
    "DOGE/USD": 7,
    "LTC/USD": 2,
    "LINK/USD": 5,
    "ADA/USD": 6,
    "AVAX/USD": 2,
    "AAVE/USD": 2,
    "UNI/USD": 3,
    "DOT/USD": 4,
    "BCH/USD": 2,
    "ALGO/USD": 5,
    "CRV/USD": 4,
    "HBAR/USD": 5,
    "PEPE/USD": 9,
    "SHIB/USD": 8,
    "TRX/USD": 6,
    "ZEC/USD": 2,
    "USDC/USD": 4,
    "HYPE/USD": 2,
    "PAXG/USD": 2,
    "NEAR/USD": 3,
    "PENGU/USD": 6,
    "RENDER/USD": 3,
    "WLD/USD": 4,
    "XLM/USD": 6,
}